#!/bin/bash
#
# Quick Reference Guide for Build & Test Scripts
# Copy and paste commands directly into terminal
#

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Microservices Build System - Quick Reference Guide        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run all tests:"
echo "  ./test.sh"
echo "  make test"
echo ""
echo "Run tests with verbose output:"
echo "  ./test.sh -v"
echo "  make test-verbose"
echo ""
echo "Test specific service:"
echo "  ./test.sh auth-service"
echo "  ./test.sh catalog-service"
echo "  ./test.sh order-service"
echo "  make test-auth-service"
echo ""

echo "🔨 BUILDING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Build all services:"
echo "  ./build.sh"
echo "  make build"
echo ""
echo "Build with clean (remove old builds first):"
echo "  ./build.sh clean"
echo "  make build-clean"
echo ""
echo "Build specific service:"
echo "  ./build.sh auth-service"
echo "  make build-auth-service"
echo ""

echo "🚀 RUNNING SERVICES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start all services:"
echo "  cd dist && ./start_all.sh"
echo "  make dist/start"
echo ""
echo "Stop all services:"
echo "  cd dist && ./stop_all.sh"
echo "  make dist/stop"
echo ""
echo "watch service logs:"
echo "  tail -f dist/logs/*.log"
echo "  make dist/logs"
echo ""
echo "Check service status:"
echo "  make dist/status"
echo ""

echo "📊 SERVICE ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Auth Service:"
echo "  API: http://localhost:8081"
echo "  Swagger: http://localhost:8081/swagger"
echo ""
echo "Catalog Service:"
echo "  API: http://localhost:8082"
echo "  Swagger: http://localhost:8082/swagger"
echo ""
echo "Order Service:"
echo "  API: http://localhost:8083"
echo "  Swagger: http://localhost:8083/swagger"
echo ""

echo "🔧 COMMON WORKFLOWS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Development setup (build + start):"
echo "  ./build.sh clean && cd dist && ./start_all.sh"
echo "  make dev/build && make dist/start"
echo ""
echo "Test all changes:"
echo "  ./test.sh && ./build.sh clean && cd dist && ./start_all.sh"
echo ""
echo "Rebuild and restart:"
echo "  make dist/stop && make build-clean && make dist/start"
echo ""
echo "Full development workflow:"
echo "  make dev"
echo ""

echo "🧹 CLEANUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Remove dist folder:"
echo "  make clean"
echo "  rm -rf dist"
echo ""
echo "Reset databases:"
echo "  rm -rf dist/data/* && cd dist && ./init_db.sh"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "View detailed documentation:"
echo "  cat SCRIPTS.md"
echo ""
echo "View Makefile help:"
echo "  make help"
echo ""
echo "View dist README:"
echo "  cat dist/README.md"
echo ""

echo ""
echo "✓ Ready to start! Run 'make help' for a full command list"
echo ""
